name: CI
on:
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Do the checkout thing
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.prSHA }}
      - name: Do the comment thing
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.client_payload.pr }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Hey @${{ github.event.client_payload.actor }}, I've packed this into an installable tgz. You can install it for testing by referencing it in your package.json like so:
              \`\`\`
              {
                  "depdendecies": {
                      "discord.js": ""
                  }
              }
              \`\`\`
              and then running \`npm install\`, or via \`npm i ""\`.
              `
            })
